import { NextRequest, NextResponse } from "next/server";
import puppeteer from "puppeteer";
import { db } from "@/lib/db";

export const dynamic = "force-dynamic"; // ensure fresh data

export async function GET(req: NextRequest) {
    try {
        const { searchParams } = new URL(req.url);
        const property_id = searchParams.get("property_id");

        console.log('property id', property_id);

        if (!property_id) {
            return NextResponse.json(
                { error: "Missing property_id" },
                { status: 400 }
            );
        }

        // 🗓 Get current month and year
        const now = new Date();
        const currentMonth = now.getMonth() + 1;
        const currentYear = now.getFullYear();

        // 📦 Fetch billing data for this property (current month)
        const [rows]: any = await db.query(
            `
      SELECT 
        b.billing_id,
        u.unit_name,
        b.total_amount_due,
        b.status,
        b.due_date,
        b.billing_period,
        b.created_at
      FROM Billing b
      JOIN Unit u ON b.unit_id = u.unit_id
      WHERE u.property_id = ?
        AND MONTH(b.created_at) = ?
        AND YEAR(b.created_at) = ?
      ORDER BY b.created_at DESC
      `,
            [property_id, currentMonth, currentYear]
        );

        if (!rows.length) {
            return NextResponse.json(
                { message: "No billing records found for this month." },
                { status: 404 }
            );
        }

        // 🧾 Generate HTML table for Puppeteer
        const html = `
      <html>
        <head>
          <style>
            body {
              font-family: 'Arial', sans-serif;
              padding: 20px;
              color: #333;
            }
            h1 {
              text-align: center;
              color: #2563eb;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin-top: 20px;
              font-size: 13px;
            }
            th, td {
              border: 1px solid #ddd;
              padding: 10px;
              text-align: left;
            }
            th {
              background-color: #f4f7fb;
              color: #111827;
              font-weight: bold;
            }
            tr:nth-child(even) {
              background-color: #f9fafb;
            }
            .footer {
              text-align: center;
              font-size: 12px;
              color: #6b7280;
              margin-top: 30px;
            }
          </style>
        </head>
        <body>
          <h1>Billing Summary – ${now.toLocaleString("default", {
            month: "long",
        })} ${currentYear}</h1>
          <table>
            <thead>
              <tr>
                <th>Billing ID</th>
                <th>Unit Name</th>
                <th>Billing Period</th>
                <th>Due Date</th>
                <th>Status</th>
                <th>Total Amount (₱)</th>
              </tr>
            </thead>
            <tbody>
              ${rows
            .map(
                (r: any) => `
                <tr>
                  <td>${r.billing_id}</td>
                  <td>${r.unit_name}</td>
                  <td>${r.billing_period ? new Date(r.billing_period).toLocaleDateString("en-PH") : "-"}</td>
                  <td>${r.due_date ? new Date(r.due_date).toLocaleDateString("en-PH") : "-"}</td>
                  <td>${r.status}</td>
                  <td>${r.total_amount_due?.toLocaleString("en-PH", {
                    style: "currency",
                    currency: "PHP",
                })}</td>
                </tr>`
            )
            .join("")}
            </tbody>
          </table>
          <div class="footer">
            Generated by UpKyp Property Management System
          </div>
        </body>
      </html>
    `;

        // 🧠 Launch Puppeteer and render PDF
        const browser = await puppeteer.launch({
            headless: "new",
            args: ["--no-sandbox", "--disable-setuid-sandbox"],
        });

        const page = await browser.newPage();
        await page.setContent(html, { waitUntil: "networkidle0" });

        const pdfBuffer = await page.pdf({
            format: "A4",
            printBackground: true,
            margin: { top: "20mm", bottom: "20mm", left: "10mm", right: "10mm" },
        });

        await browser.close();

        // 📤 Return PDF file
        return new NextResponse(pdfBuffer, {
            status: 200,
            headers: {
                "Content-Type": "application/pdf",
                "Content-Disposition": `attachment; filename="Billing_Summary_${currentMonth}_${currentYear}.pdf"`,
            },
        });
    } catch (error) {
        console.error("❌ PDF generation failed:", error);
        return NextResponse.json(
            { error: "Failed to generate billing summary." },
            { status: 500 }
        );
    }
}
