// app/api/landlord/payments/exportReport/route.ts
import { NextResponse } from "next/server";
import puppeteer from "puppeteer";
import { db } from "@/lib/db";
import { formatCurrency, formatDate } from "@/utils/formatter/formatters";

export const dynamic = "force-dynamic";

export async function GET(req: Request) {
    const { searchParams } = new URL(req.url);
    const landlord_id = searchParams.get("landlord_id");
    const property_id = searchParams.get("property_id");
    const month = searchParams.get("month");

    if (!landlord_id) {
        return NextResponse.json({ error: "Missing landlord_id" }, { status: 400 });
    }

    let query = `
    SELECT 
      p.payment_id, 
      pr.property_name, 
      p.payment_type, 
      p.amount_paid, 
      p.payment_status, 
      p.payment_date, 
      p.receipt_reference
    FROM Payment p
    JOIN LeaseAgreement la ON la.agreement_id = p.agreement_id
    JOIN Unit u ON u.unit_id = la.unit_id
    JOIN Property pr ON pr.property_id = u.property_id
    WHERE pr.landlord_id = ?
  `;

    const params: any[] = [landlord_id];
    if (property_id) {
        query += " AND pr.property_id = ?";
        params.push(property_id);
    }
    if (month) {
        query += " AND DATE_FORMAT(p.payment_date, '%Y-%m') = ?";
        params.push(month);
    }

    query += " ORDER BY p.payment_date DESC";

    const [rows]: any = await db.query(query, params);

    // 🧾 Generate HTML for Puppeteer
    const now = new Date();
    const html = `
  <html>
    <head>
      <style>
        body {
          font-family: 'Arial', sans-serif;
          padding: 24px;
          color: #333;
        }
        h1 {
          text-align: center;
          color: #2563eb;
          margin-bottom: 5px;
        }
        h3 {
          text-align: center;
          color: #555;
          margin-top: 0;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-top: 20px;
          font-size: 13px;
        }
        th, td {
          border: 1px solid #ddd;
          padding: 8px 10px;
          text-align: left;
        }
        th {
          background-color: #f3f4f6;
          color: #111827;
        }
        tr:nth-child(even) {
          background-color: #f9fafb;
        }
        .footer {
          text-align: center;
          font-size: 11px;
          color: #6b7280;
          margin-top: 30px;
        }
      </style>
    </head>
    <body>
      <h1>Payment Report</h1>
      <h3>${month ? month : "All Months"} • ${property_id ? "Filtered Property" : "All Properties"}</h3>
      <table>
        <thead>
          <tr>
            <th>Payment ID</th>
            <th>Property</th>
            <th>Type</th>
            <th>Amount Paid</th>
            <th>Status</th>
            <th>Date Paid</th>
            <th>Reference</th>
          </tr>
        </thead>
        <tbody>
          ${rows
        .map(
            (r: any) => `
              <tr>
                <td>${r.payment_id}</td>
                <td>${r.property_name}</td>
                <td>${r.payment_type}</td>
                <td>${formatCurrency(r.amount_paid)}</td>
                <td>${r.payment_status}</td>
                <td>${formatDate(r.payment_date)}</td>
                <td>${r.receipt_reference || "—"}</td>
              </tr>`
        )
        .join("")}
        </tbody>
      </table>
      <div class="footer">
        Generated by UpKyp • ${now.toLocaleString()}
      </div>
    </body>
  </html>
  `;

    // 🖨️ Generate PDF via Puppeteer
    const browser = await puppeteer.launch({
        headless: true,
        args: ["--no-sandbox", "--disable-setuid-sandbox"],
    });
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });
    const pdfBuffer = await page.pdf({
        format: "A4",
        printBackground: true,
    });
    await browser.close();

    return new NextResponse(pdfBuffer, {
        headers: {
            "Content-Type": "application/pdf",
            "Content-Disposition": "attachment; filename=Payment_Report.pdf",
        },
    });
}
